/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slackerOne_JPP */

#ifndef _Included_com_slackerOne_JPP
#define _Included_com_slackerOne_JPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_slackerOne_JPP
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_slackerOne_JPP_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_slackerOne_JPP
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_slackerOne_JPP_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_slackerOne_JPP
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_slackerOne_JPP_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_slackerOne_JPP
 * Method:    getFirmwareVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_slackerOne_JPP_getFirmwareVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_slackerOne_JPP
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_slackerOne_JPP_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
